name: Deploy Data Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-datascience-notebook
  AWS_REGION: us-east-1
  ECR_REGISTRY: 274127640471.dkr.ecr.us-east-1.amazonaws.com
  INSTANCE_TYPE: t2.micro
  INSTANCE_AMI: ami-0885b1f6bd170450c
  KEY_NAME: my-ec2-key

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create EC2 instance
        id: ec2
        uses: easingthemes/ssh-deploy@v2.4.13
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ec2-key: ${{ env.KEY_NAME }}
          ec2-user: ubuntu
          region: ${{ env.AWS_REGION }}
          instance-type: ${{ env.INSTANCE_TYPE }}
          image-id: ${{ env.INSTANCE_AMI }}
          vpc-subnet-id: ${{ secrets.SUBNET_ID }}
          security-group-id: ${{ secrets.SECURITY_GROUP_ID }}
          wait-for-ssh: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clone repository into EC2 instance
        uses: easingthemes/ssh-deploy@v2.4.13
        with:
          command: |
            git clone https://github.com/Primus-Learning/data-pipeline-docker.git
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ec2-key: ${{ env.KEY_NAME }}
          ec2-user: ubuntu
          host: ${{ steps.ec2.outputs.public-ip }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Docker in EC2 instance
        uses: easingthemes/ssh-deploy@v2.4.13
        with:
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker ubuntu
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ec2-key: ${{ env.KEY_NAME }}
          ec2-user: ubuntu
          host: ${{ steps.ec2.outputs.public-ip }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS CLI in EC2 instance
        uses: easingthemes/ssh-deploy@v2.4.13
        with:
          command: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ${{ env.AWS_REGION }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ec2-key: ${{ env.KEY_NAME }}
          ec2-user: ubuntu
          host: ${{ steps.ec2.outputs.public-ip }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image in EC2 instance
        uses: easingthemes/ssh-deploy@v2.4.13
        with:
          command: |
            cd
