name: Build and push Docker image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-datascience-notebook
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  ECR_REGISTRY: 274127640471.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create EC2 Instance
      id: ec2
      uses: appleboy/ec2-instance@master
      with:
        name: my-instance
        key_name: my-key-pair
        security_group_id: my-security-group
        subnet_id: my-subnet
        ami_id: ami-0c94855ba95c71c99
        instance_type: t2.micro
        wait_timeout: 120
        tags: name=my-instance
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Install Docker and Git
      uses: appleboy/ansible-action@v0.1.2
      with:
        playbook: |
          - name: Install Docker and Git
            hosts: all
            become: true
            vars:
              docker_version: "20.10.12"
            tasks:
              - name: Install Python and pip
                become: true
                apt:
                  name: [python3, python3-pip]
                  state: present

              - name: Install Docker
                become: true
                apt:
                  name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
                  state: present
              - name: Add Docker apt-key
                become: true
                shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              - name: Add Docker repository
                become: true
                shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              - name: Install Docker engine
                become: true
                apt:
                  name: docker-ce={{ docker_version }} docker-ce-cli={{ docker_version }} containerd.io
                  state: present
              - name: Add user to Docker group
                become: true
                user:
                  name: ubuntu
                  groups: docker
                  append: yes
              - name: Install Git
                become: true
                apt:
                  name: git
                  state: present

    - name: Clone repository
      run: |
        git clone https://github.com/Primus-Learning/data-pipeline-docker.git
        cd data-pipeline-docker
        git checkout main

    - name: Build Docker image
      run: |
        cd data-pipeline-docker
        docker build -t ${{ env.IMAGE_NAME }} .

    - name: Push Docker image to ECR
      run: |
        $(aws ecr get-login --no-include-email
